class Header(object):
    x_sumo_source = 'X-Sumo-Name'
    x_sumo_host = 'X-Sumo-Host'
    x_sumo_category = 'X-Sumo-Category'
    content_encoding = 'Content-Encoding'
    accept = 'Accept'
    content_type = 'Content-Type'
    authorization = 'Authorization'
    query = 'query'
    row_id = 'rowId'
    start_time = 'startTime'
    end_time = 'endTime'
    requested_data_points = 'requestedDataPoints'
    max_data_points = 'maxDataPoints'
